// Offline native and bundled Pi 1.0 load, TUI behavior and cleanup probe.
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
const repo = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const manifest = JSON.parse(readFileSync(join(repo, 'package.json'), 'utf8'));
const root = mkdtempSync(join(repo, '.git/pi1-host-'));
const agentDir = join(root, 'agent');
mkdirSync(agentDir); mkdirSync(join(root, '.pi'));
process.env.PI_CODING_AGENT_DIR = agentDir;
process.env.PI_FABRIC_PARENT_RUN = '';
const host = process.env.PI1_HOST_PACKAGE;
const hostEntry = process.env.PI1_HOST_ENTRY === 'bundle' ? 'dist/bundle/index.js' : 'dist/index.js';
const sdk = await import(host ? pathToFileURL(join(host, hostEntry)).href : '@earendil-works/pi-coding-agent');
assert.equal(sdk.VERSION, '1.0.0');
assert.equal((await import('@earendil-works/pi-coding-agent')).VERSION, '1.0.0');
const constructors = ['AgentSession', 'InteractiveMode', 'ModelSelectorComponent', 'FooterComponent', 'CustomEditor'];
globalThis[Symbol.for('pi1.ui.host')] = sdk;
const identity = join(root, 'identity.ts');
writeFileSync(identity, `import * as sdk from '@earendil-works/pi-coding-agent'; export default function () { for (const key of ${JSON.stringify(constructors)}) if (sdk[key] !== globalThis[Symbol.for('pi1.ui.host')][key]) throw new Error('Duplicate host: ' + key); }`);
const targets = [[sdk.FooterComponent.prototype, 'render'], [sdk.InteractiveMode.prototype, 'showSessionSelector'], [sdk.InteractiveMode.prototype, 'showTreeSelector'], [sdk.ModelSelectorComponent.prototype, 'loadModelsFromSnapshot'], [sdk.ModelSelectorComponent.prototype, 'sortModels'], [sdk.AgentSession.prototype, '_cycleScopedModel']];
const originals = targets.map(([p, key]) => p[key]);
const settingsManager = sdk.SettingsManager.inMemory({ compaction: { enabled: false }, retry: { enabled: false } });
const runtime = await sdk.ModelRuntime.create({ authPath: join(agentDir, 'auth.json'), modelsPath: null, allowModelNetwork: false, refreshOnCreate: false });
const loader = new sdk.DefaultResourceLoader({ cwd: root, agentDir, settingsManager, noExtensions: true, noSkills: true, noPromptTemplates: true, noThemes: true, noContextFiles: true, additionalExtensionPaths: [...manifest.pi.extensions.map(p => resolve(repo, p)), identity] });
let session;
try {
  await loader.reload(); assert.deepEqual(loader.getExtensions().errors, []);
  const owned = loader.getExtensions().extensions.find(e => manifest.pi.extensions.some(p => e.resolvedPath === resolve(repo, p)));
  assert(owned); assert(owned.handlers.size + owned.commands.size > 0);
  const manager = sdk.SessionManager.inMemory(root);
  manager.appendMessage({ role: 'user', content: 'host probe', timestamp: Date.now() });
  ({ session } = await sdk.createAgentSession({ cwd: root, agentDir, modelRuntime: runtime, resourceLoader: loader, settingsManager, sessionManager: manager }));
  const errors = []; session.extensionRunner.onError(e => errors.push(e));
  await session.bindExtensions({});
  for (const [i, [p, key]] of targets.entries()) assert.equal(p[key], originals[i], 'headless must not patch UI');
  sdk.initTheme('dark', false);
  let factory, customCalls = 0;
  const ui = { ...session.extensionRunner.createContext().ui, theme: session.extensionRunner.createContext().ui.theme, notify() {}, getEditorComponent: () => factory, setEditorComponent: f => { factory = f; }, custom: async create => { customCalls++; const c = create({ requestRender() {}, terminal: { rows: 30, columns: 80 } }, session.extensionRunner.createContext().ui.theme, {}, () => {}); c.focused = true; c.invalidate(); assert(Array.isArray(c.render(80))); c.dispose?.(); return undefined; } };
  session.extensionRunner.setUIContext(ui, 'tui');
  await session.extensionRunner.emit({ type: 'session_start', reason: 'reload' });
  assert(owned.commands.has('toggle-skills'));
  const skillDir = join(agentDir, 'skills/probe'); mkdirSync(skillDir, { recursive: true });
  const skill = join(skillDir, 'SKILL.md'); writeFileSync(skill, '---\nname: probe\ndescription: host probe\n---\nInstructions\n');
  await session.extensionRunner.emit({ type: 'session_start', reason: 'reload' });
  const ctx = session.extensionRunner.createCommandContext();
  await owned.commands.get('toggle-skills').handler('disable probe', ctx);
  assert.match(readFileSync(skill, 'utf8'), /disable-model-invocation: true/);
  await owned.commands.get('toggle-skills').handler('enable probe', ctx);
  assert(!readFileSync(skill, 'utf8').includes('disable-model-invocation: true'));
  await session.extensionRunner.emit({ type: 'session_shutdown', reason: 'quit' });
  assert.deepEqual(errors, []);
  for (const [i, [p, key]] of targets.entries()) assert.equal(p[key], originals[i], 'shutdown restores ' + key);
  assert.equal(factory, undefined);
  console.log(JSON.stringify({ repo: manifest.name, pi: sdk.VERSION, hostEntry, registrations: { handlers: owned.handlers.size, commands: owned.commands.size }, behavior: 'passed', cleanup: 'passed' }));
} finally { session?.dispose(); delete globalThis[Symbol.for('pi1.ui.host')]; rmSync(root, { recursive: true, force: true }); }
